### ISSUE TITLE
Bug: Er lijkt een dependency probleem in de packadges te zitten

### ISSUE THREAD

**Issue by rubenvdlinde** [Gemeente-DenHaag/nl-portal-libraries#6]
Een clean install levert het volgende probleem op

![dependency prop](https://user-images.githubusercontent.com/4021899/128991626-543c49b9-2c63-472b-acf0-79ece2a0e268.PNG)

**Comment by mritense** [comment]
Opgelost, zie readme, dependencies worden geïnstalleerd met lerna bootstrap.
